"""Type stubs for torch.vulkan module."""

from typing import Any

def is_available() -> bool: ...
def synchronize() -> None: ...
def empty_cache() -> None: ...
def memory_allocated() -> int: ...
def max_memory_allocated() -> int: ...
def reset_peak_memory_stats() -> None: ...
def memory_reserved() -> int: ... 