# Base configuration schema for all test regimens
# All test configs should extend this base config

# Core validation parameters
validation:
  tolerances:
    # General tolerances
    base: 1.0e-5
    finite_diff: 1.0e-3
    tensor_compare: 1.0e-8
    small_angle: 1.0e-4
    
    # Fiber bundle tolerances
    projection: 1.0e-5
    trivialization: 1.0e-5
    transition: 1.0e-5
    connection: 1.0e-5
    transport: 1.0e-4
    metric: 1.0e-5
    torsion_free: 1.0e-5
    vertical_preservation: 1.0e-5
    linearity: 1.0e-5
    structure_group: 1.0e-5
    skew_symmetry: 1.0e-5
    lie_bracket: 1.0e-5
    horizontal: 1.0e-4
    path_independence: 1.0e-4
    norm_preservation: 1.0e-4
    loop_triviality: 1.0e-4
    symmetry: 1.0e-5
    metric_compatibility: 1.0e-5
    
    # Quantum tolerances
    state_norm: 1.0e-6
    phase_comparison: 1.0e-5
    geometric_phase: 1.0e-4
    quantum_metric: 1.0e-5
    berry_connection: 1.0e-5
    
  thresholds:
    convergence: 1.0e-6
    stability: 1.0e-5
    entanglement: 0.9
    defrag: 0.8
    min_scale: 1.0e-6
    max_scale: 5.0
    max_norm: 10.0

# Core geometric parameters
geometric:
  manifold_dim: 3
  fiber_dim: 3
  motive_rank: 2
  num_primes: 4
  fisher_rao_weight: 0.5
  quantum_weight: 0.1
  stress_energy_weight: 0.5
  dt: 0.01
  min_scale: 1.0e-6
  max_scale: 5.0
  max_norm: 10.0
  curvature_bounds: [-1.0, 1.0]

# Data types
dtypes:
  default: "float32"
  quantum: "complex64"

# Test constants
test_constants:
  vector_scales: [0.1, 1.0, 10.0]
  test_norms: [0.1, 1.0, 10.0]
  max_path_length: 10.0
  arc_angle: 0.7853981633974483  # pi/4
  max_skew_error: 5.0e-5
  max_torsion_error: 5.0e-5
  max_group_error: 5.0e-5

# Validation methods
validation_methods:
  parallel_transport: ["schild", "exponential"]
  max_iterations: 100

# Performance parameters
performance:
  dimensions:
    hidden: 64
    latent: 32
    embedding: 128
  batch_sizes:
    geometric: 32
    quantum: 16
    pattern: 64
    flow: 32
  test_cases:
    num_samples: 1000
    warmup_iters: 10
    test_iters: 100