# Base configuration schema for all test regimens
# All test configs should extend this base config

# Required parameters for fiber bundle tests
fiber_bundle:
  base_dim: 3
  fiber_dim: 3
  batch_size: 32
  dtype: "float32"
  tolerance: 1e-5

# Fiber bundle test specific parameters
fiber_bundle_tests:
  test_tolerances:
    projection: 1e-5
    trivialization: 1e-5
    transition: 1e-5
    connection: 1e-5
    transport: 1e-4
    metric: 1e-5
    torsion_free: 1e-5
    vertical_preservation: 1e-5
    linearity: 1e-5
    structure_group: 1e-5
    skew_symmetry: 1e-5
    lie_bracket: 1e-5
    finite_diff: 1e-3
    horizontal: 1e-4
    path_independence: 1e-4
    norm_preservation: 1e-4
    loop_triviality: 1e-4
    symmetry: 1e-5
    metric_compatibility: 1e-5

# Geometric test parameters
geometric_tests:
  dimensions: 3
  num_heads: 8
  hidden_dim: 64
  vector_scales: [0.1, 1.0, 10.0]
  test_norms: [0.1, 1.0, 10.0]

# Parallel transport parameters
parallel_transport:
  methods: ["schild", "exponential"]
  test_cases: 10
  section_batch_size: 16
  path_points: 100
  max_path_length: 10.0

# Quantum geometric parameters
quantum_geometric:
  fisher_rao_weight: 0.5
  quantum_weight: 0.1
  stress_energy_weight: 0.5
  manifold_dim: 3
  dt: 0.01

# Memory management parameters
memory_management:
  max_cached_tensors: 1000
  defrag_threshold: 0.8
  gc_frequency: 1000
  tensor_lifecycle: "normal"