---
# Debug test configuration extending base.yaml
# This configuration is used for debugging and development with relaxed tolerances

defaults:
  - base

# Hardware profile
hardware_profile:
  name: "debug"
  description: "Configuration for debugging and development"
  target_hardware:
    ram_gb: 8
    cpu: "minimal"
    memory: "minimal"

# Performance settings
performance:
  batch_sizes:
    default: 16
    geometric: 8
    quantum: 8
    section: 8
  dimensions:
    hidden: 32
    heads: 4
  test_cases:
    parallel_transport: 5
    path_points: 50
  cache:
    max_tensors: 100
    gc_frequency: 100

# Override validation tolerances for debugging
validation:
  tolerances:
    base: 1e-4
    finite_diff: 1e-2
    tensor_compare: 1e-6
    small_angle: 1e-3
    
    # Fiber bundle tolerances
    projection: 1e-4
    trivialization: 1e-4
    transition: 1e-4
    connection: 1e-4
    transport: 1e-3
    metric: 1e-4
    torsion_free: 1e-4
    vertical_preservation: 1e-4
    linearity: 1e-4
    structure_group: 1e-4
    skew_symmetry: 1e-4
    lie_bracket: 1e-4
    horizontal: 1e-3
    path_independence: 1e-3
    norm_preservation: 1e-3
    loop_triviality: 1e-3
    symmetry: 1e-4
    metric_compatibility: 1e-4
    
    # Quantum tolerances
    state_norm: 1e-5
    phase_comparison: 1e-4
    geometric_phase: 1e-3
    quantum_metric: 1e-4
    berry_connection: 1e-4
    
  thresholds:
    convergence: 1e-5
    stability: 1e-4
    entanglement: 0.8