# Test configuration for debugging (absolute minimal settings)
# Extends base.yaml with minimal values for debugging

# Hardware profile
hardware_profile:
  name: "debug"
  description: "Extreme minimal configuration for debugging"
  target_hardware:
    ram_gb: 2
  cpu: "minimal"
  memory: "minimal"

# Override base parameters with minimal values
fiber_bundle:
  base_dim: 2
  fiber_dim: 2
  batch_size: 1
  dtype: "float32"
  tolerance: 1e-4

# Fiber bundle test specific parameters
fiber_bundle_tests:
  structure_group_dim: 2
  test_paths:
    circular_points: 10
    figure8_points: 20
    max_angle: 2 * pi
  test_vectors:
    initial_norm: 1.0
    perturbation_scale: 0.1

geometric_tests:
  dimensions: 2
  num_heads: 1
  hidden_dim: 8
  vector_scales: [0.01]
  test_norms: [0.01]

parallel_transport:
  methods: ["schild"]
  test_cases: 1
  section_batch_size: 1
  path_points: 10
  max_path_length: 1.0

quantum_geometric:
  fisher_rao_weight: 0.1
  quantum_weight: 0.01
  stress_energy_weight: 0.1
  manifold_dim: 2
  hidden_dim: 4
  dt: 0.1

memory_management:
  max_cached_tensors: 100
  defrag_threshold: 0.5
  gc_frequency: 100
  tensor_lifecycle: "short"