# Test configuration for server hardware (high-performance servers)
hardware_profile:
  name: "server"
  description: "Configuration for high-performance servers"
  target_hardware:
    ram_gb: 128
    cpu: "high_end"
    memory: "high_end"

geometric_tests:
  batch_size: 512
  max_dim: 1024
  num_samples: 10000

pattern_tests:
  max_patterns: 1024
  pattern_size: 512
  num_iterations: 1000

performance_tests:
  warmup_iters: 10
  test_iters: 100
  max_batch_size: 1024