# Test configuration for server hardware (high-performance servers)
# Contains only performance-related settings that override base.yaml

hardware_profile:
  name: "server"
  description: "Configuration for high-performance servers"
  target_hardware:
    ram_gb: 128
    cpu: "high_end"
    memory: "high_end"

# Performance-related parameters
fiber_bundle:
  batch_size: 512

geometric_tests:
  batch_size: 512
  max_samples: 10000
  max_iterations: 1000

pattern_tests:
  batch_size: 512
  max_patterns: 1024
  pattern_size: 512
  num_iterations: 1000

parallel_transport:
  batch_size: 128
  path_points: 500
  test_cases: 50

memory_management:
  max_cached_tensors: 100000
  gc_frequency: 5000

quantum_geometric:
  dt: 0.001
  batch_size: 512

quantum_arithmetic:
  batch_size: 512
  max_iterations: 1000