# Server test configuration extending base.yaml
# This configuration is for high-performance servers

defaults:
  - base

# Hardware profile
hardware_profile:
  name: "server"
  description: "Configuration for high-performance servers"
  target_hardware:
    ram_gb: 128
    cpu: "high_end"
    memory: "high_end"

# Performance settings
performance:
  batch_sizes:
    default: 512
    geometric: 256
    quantum: 256
    section: 128
  dimensions:
    hidden: 1024
    heads: 16
  test_cases:
    parallel_transport: 20
    path_points: 200
  cache:
    max_tensors: 10000
    gc_frequency: 5000

# Test paths
test_paths:
  circular_points: 200
  figure8_points: 400
  max_angle: 6.283185307179586  # 2 * pi

# Test vectors
test_vectors:
  initial_norm: 1.0
  perturbation_scale: 0.1

# Pattern tests
pattern_tests:
  max_patterns: 1024
  pattern_size: 512
  num_iterations: 1000

# Performance tests
performance_tests:
  warmup_iters: 10
  test_iters: 100
  max_batch_size: 1024