# Test configuration for standard hardware (workstations with decent resources)
# Contains only performance-related settings that override base.yaml

# Hardware profile
hardware_profile:
  name: "standard"
  description: "Configuration for workstations with decent resources"
  target_hardware:
    ram_gb: 32
    cpu: "standard"
    memory: "standard"

# Performance-related parameters
fiber_bundle:
  batch_size: 32  # Reduced to prevent dimension overflow

geometric:
  batch_size: 32
  max_samples: 1000
  max_iterations: 100

pattern_tests:
  batch_size: 32
  max_patterns: 128
  pattern_size: 32  # Reduced to prevent dimension overflow
  num_iterations: 200

parallel_transport:
  batch_size: 16
  path_points: 50  # Reduced to prevent dimension overflow
  test_cases: 10

memory_management:
  max_cached_tensors: 5000
  gc_frequency: 500

quantum:
  dt: 0.005  # Smaller timestep for better precision
  batch_size: 32
  max_iterations: 100