# Test configuration for standard hardware (workstations with decent resources)
# Contains only performance-related settings that override base.yaml

# Hardware profile
hardware_profile:
  name: "standard"
  description: "Configuration for workstations with decent resources"
  target_hardware:
    ram_gb: 32
    cpu: "standard"
    memory: "standard"

# Performance-related parameters
fiber_bundle:
  batch_size: 32  # Reduced to prevent dimension overflow

geometric:
  batch_size: 32
  max_samples: 1000
  max_iterations: 100

pattern_tests:
  batch_size: 32
  max_patterns: 128
  pattern_size: 32  # Reduced to prevent dimension overflow
  num_iterations: 200

parallel_transport:
  batch_size: 16
  path_points: 50  # Reduced to prevent dimension overflow
  test_cases: 10

memory_management:
  max_cached_tensors: 5000
  gc_frequency: 500

quantum:
  dt: 0.005  # Smaller timestep for better precision
  batch_size: 32
  max_iterations: 100

quantum_geometric:
  dt: 0.01  # Default timestep
  fisher_rao_weight: 0.5  # Weight for Fisher-Rao metric
  quantum_weight: 0.1  # Weight for quantum effects
  stress_energy_weight: 0.5  # Weight for stress-energy tensor

geometric_tests: 
#Bigger numbers here cause the following
# =================================== short test summary info ===================================
# FAILED tests/test_validation/test_model_geometric.py::TestModelGeometricValidator::test_geometric_preservation - AssertionError: Attention does not preserve geometric structure for scale 1.0
# =============================== 1 failed, 104 passed in 31.69s ================================
  dimensions: 32  # Match quantum bridge hidden_dim
  num_heads: 4  # Fewer heads for better stability
  hidden_dim: 32  # Match quantum bridge hidden_dim

quantum_arithmetic:
  dtype: float32  # Fixed data type for quantum operations
  manifold_dim: 3  # Manifold dimension for quantum operations
  hidden_dim: 32  # Hidden dimension for quantum operations
  motive_rank: 2  # Rank of the motive
  num_primes: 4  # Number of primes for arithmetic operations
  batch_size: 16  # Batch size for quantum operations
  min_scale: 1.0e-6  # Minimum scale for height computations
  max_scale: 5.0  # Maximum scale for height computations
  max_norm: 10.0  # Maximum norm for curvature bounds
  fisher_rao_weight: 0.5  # Weight for Fisher-Rao metric
  tolerances:
    state_norm: 1.0e-5
    phase_comparison: 1.0e-4
    geometric_phase: 1.0e-3
    quantum_metric: 1.0e-4
    berry_connection: 1.0e-4
  validation:
    max_iterations: 50
    convergence_threshold: 1.0e-5
    stability_threshold: 1.0e-4
    entanglement_threshold: 0.8