# Standard test configuration extending base.yaml
# This configuration is for workstations with decent resources

defaults:
  - base

# Hardware profile
hardware_profile:
  name: "standard"
  description: "Configuration for workstations with decent resources"
  target_hardware:
    ram_gb: 32
    cpu: "standard"
    memory: "standard"

# Performance settings
performance:
  batch_sizes:
    default: 128
    geometric: 64
    quantum: 64
    section: 32
  dimensions:
    hidden: 64
    heads: 8
  test_cases:
    parallel_transport: 10
    path_points: 100
  cache:
    max_tensors: 1000
    gc_frequency: 1000

# Test paths
test_paths:
  circular_points: 100
  figure8_points: 200
  max_angle: 6.283185307179586  # 2 * pi

# Test vectors
test_vectors:
  initial_norm: 1.0
  perturbation_scale: 0.1

# Numerical constants
numerical_constants:
  epsilons:
    finite_diff: 1e-6
    small_angle: 1e-4
    tensor_compare: 1e-8
  test_values:
    small_loop_scale: 0.1
    arc_angle: 0.7853981633974483  # pi/4
    max_skew_error: 5e-5
    max_torsion_error: 5e-5
    max_group_error: 5e-5