# Test configuration for standard hardware (workstations with decent resources)
hardware_profile:
  name: "standard"
  description: "Configuration for workstations with decent resources"
  target_hardware:
    ram_gb: 32
    cpu: "standard"
    memory: "standard"

geometric_tests:
  batch_size: 128
  max_dim: 256
  num_samples: 1000

pattern_tests:
  max_patterns: 256
  pattern_size: 128
  num_iterations: 200

performance_tests:
  warmup_iters: 5
  test_iters: 20
  max_batch_size: 256