# Standard test configuration extending base.yaml
# This configuration is for workstations with decent resources

defaults:
  - base

# Hardware profile
hardware_profile:
  name: "standard"
  description: "Configuration for workstations with decent resources"
  target_hardware:
    ram_gb: 32
    cpu: "standard"
    memory: "standard"

# Fiber bundle parameters
fiber_bundle:
  batch_size: 128
  tolerance: 1.0e-5
  dimensions:
    manifold: 3
    fiber: 3
    hidden: 64
  parameters:
    fisher_rao_weight: 0.5
    quantum_weight: 0.1
    stress_energy_weight: 0.5
  validation:
    max_iterations: 100
    parallel_transport_methods: ["schild", "exponential"]
    stability_threshold: 1.0e-5

# Quantum geometric parameters
quantum_geometric:
  manifold_dim: 3
  fiber_dim: 3
  dt: 0.01
  num_steps: 100
  batch_size: 64
  tolerance: 1.0e-5
  stability_threshold: 1.0e-5
  max_iterations: 100
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001

# Geometric test parameters
geometric_tests:
  dimensions: 3
  hidden_dim: 64
  batch_size: 64
  num_samples: 1000
  num_iterations: 100
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  tolerance: 1.0e-5
  stability_threshold: 1.0e-5

# Performance settings
performance:
  batch_sizes:
    default: 128
    geometric: 64
    quantum: 64
    section: 32
  dimensions:
    hidden: 64
    heads: 8
  test_cases:
    parallel_transport: 10
    path_points: 100
  cache:
    max_tensors: 1000
    gc_frequency: 1000

# Test paths
test_paths:
  circular_points: 100
  figure8_points: 200
  max_angle: 6.283185307179586  # 2 * pi

# Test vectors
test_vectors:
  initial_norm: 1.0
  perturbation_scale: 0.1

# Numerical constants
numerical_constants:
  epsilons:
    finite_diff: 1e-6
    small_angle: 1e-4
    tensor_compare: 1e-8
  test_values:
    small_loop_scale: 0.1
    arc_angle: 0.7853981633974483  # pi/4
    max_skew_error: 5e-5
    max_torsion_error: 5e-5
    max_group_error: 5e-5