# Test configuration for small hardware (laptops with limited resources)
# Contains only performance-related settings that override base.yaml

hardware_profile:
  name: "tiny"
  description: "Configuration for laptops with limited resources"
  target_hardware:
    ram_gb: 16
    cpu: "minimal"
    memory: "minimal"

# Performance-related parameters
fiber_bundle:
  batch_size: 16

geometric:
  batch_size: 16
  max_samples: 200
  max_iterations: 50

pattern_tests:
  batch_size: 16
  max_patterns: 32
  pattern_size: 16
  num_iterations: 50

parallel_transport:
  batch_size: 8
  path_points: 25
  test_cases: 5

memory_management:
  max_cached_tensors: 1000
  gc_frequency: 100

quantum:
  dt: 0.01
  batch_size: 16
  max_iterations: 50