# Test configuration for small hardware (laptops with limited resources)
# Contains only performance-related settings that override base.yaml

hardware_profile:
  name: "tiny"
  description: "Configuration for laptops with limited resources"
  target_hardware:
    ram_gb: 16
    cpu: "minimal"
    memory: "minimal"

# Performance-related parameters
fiber_bundle:
  batch_size: 32

geometric_tests:
  batch_size: 32
  max_samples: 500
  max_iterations: 50

pattern_tests:
  batch_size: 32
  max_patterns: 64
  pattern_size: 64
  num_iterations: 100

parallel_transport:
  batch_size: 16
  path_points: 100
  test_cases: 10

memory_management:
  max_cached_tensors: 1000
  gc_frequency: 100

quantum_geometric:
  dt: 0.01
  batch_size: 32

quantum_arithmetic:
  batch_size: 32
  max_iterations: 50