# Test configuration for small hardware (laptops with limited resources)
hardware_profile:
  name: "tiny"
  description: "Configuration for laptops with limited resources"
  target_hardware:
    ram_gb: 16
    cpu: "minimal"
    memory: "minimal"

geometric_tests:
  batch_size: 32
  max_dim: 64
  num_samples: 500

pattern_tests:
  max_patterns: 64
  pattern_size: 64
  num_iterations: 100

performance_tests:
  warmup_iters: 3
  test_iters: 10
  max_batch_size: 64