name: CI (Disabled)
on:
  workflow_dispatch:  # This means the workflow will only run manually, effectively disabling automatic runs

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI
        run: echo "CI testing is currently disabled"
