name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create docs build directory
        run: |
          mkdir -p docs/_build/html
          cp docs/*.md docs/_build/html/
          # Create an index.html that links to all .md files
          echo "<html><head><title>Documentation</title></head><body><h1>Documentation</h1><ul>" > docs/_build/html/index.html
          for f in docs/*.md; do
            filename=$(basename "$f" .md)
            echo "<li><a href='$filename.md'>$filename</a></li>" >> docs/_build/html/index.html
          done
          echo "</ul></body></html>" >> docs/_build/html/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
